stages:
  - test
  - coverage

test_template: &test_job
  image: python:3.6
  tags:
    - docker
  script:
    - pip3 install -r requirements.txt
    - pip3 install -r requirements-dev.txt
  artifacts:
    paths:
      - .coverage.*

python 2.7:
  <<: *test_job
  image: python:2.7
  script: tox -epy27
python 3.3:
  <<: *test_job
  image: python:3.3
  script: tox -epy33
python 3.4:
  <<: *test_job
  image: python:3.4
  script: tox -epy34
python 3.5:
  <<: *test_job
  script: tox -epy35
python 3.6:
  <<: *test_job
  script: tox -epy36
flake8:
  <<: *test_job
  image: python:3.5
  script:
    - tox -epep8

coverage:
  <<: *test_job
  stage: coverage
  script:
    - tox -ecoverage
  artifacts:
    paths:
      - htmlcov/
  when: always

pip:test:
  <<: *test_job
  stage: deploy
  script:
    - make pkg-install
    - make pkg-dist
